name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python Exam 2024
      id: python-exam-2024
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 19
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-EXAM-2024_RESULTS: "${{steps.python-exam-2024.outputs.result}}"
      with:
        runners: python-exam-2024
